# Generated by Django 3.2.8 on 2021-10-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=180, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hospital_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('oxygen_available', models.FloatField(blank=True, null=True)),
                ('oxygen_supply', models.FloatField(blank=True, null=True)),
                ('userlink', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
