# Generated by Django 3.2.8 on 2021-10-21 13:58

from django.db import migrations, models
import oxygen.models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[oxygen.models.check_num]),
        ),
    ]
